[tool.poetry]
name = "poop"
version = "0.1.0"
description = "Python Object-Oriented Programming"
authors = ["cassiobotaro <cassiobotaro@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.9"
forbiddenfruit = "^0.1.3"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
