name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.14", "3.14t"]
        experimental: [false]
        include:
          - python-version: "3.15"
            experimental: true
    steps:
      - uses: actions/checkout@v7

      - uses: astral-sh/setup-uv@v7
        with:
          python-version: ${{ matrix.python-version }}
          enable-cache: true

      - run: uv sync --dev

      - run: uv run ruff check
      - run: uv run ruff format --check
      - run: uv run ty check poop/ tests/
      - run: uv run pytest
